### ISSUE TITLE
FYI: torchao nightly Windows easy install, no need to install from source

### ISSUE THREAD

**Issue by jepjoo** [woct0rdho/triton-windows#17]
I noticed some edits in the README here which still instruct to install from source.

This installs nightly build, currently 0.7.0.

`pip install --pre torchao --index-url https://download.pytorch.org/whl/nightly/cu121 # full options are cpu/cu118/cu121/cu124`

**Comment by woct0rdho** [comment]
Thank you! I've updated the README
