### ISSUE TITLE
deleting the correct cache folder in readme

### ISSUE THREAD

**Issue by sasasqt** [woct0rdho/triton-windows#23]
Hi,
in readme it mentioned to delete `C:\Users\<your username>\.triton\cache\`

but due to the access premission of temp file on windows the actual folder to delete should also inlcude this path: `C:\Users\<your username>\AppData\Local\Temp\torchinductor_USERNAME\triton\0`

this fixed the following error: (__triton_launcher.pyd failed to load)
> File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
> ImportError: DLL load failed while importing __triton_launcher: The specified module could not be found.

also for pytorch<2.6.0, manually modify codecache.py https://github.com/pytorch/pytorch/commit/d5035f0aabeb1811ce2d66ccd92d356325883107#diff-c9b517f8db609ffa866804dfa2689188a4fee20abacaa0b0dca91625c1b5cb8dR485
fixed the  `FileExistsError: [WinError 183] Cannot create a file when that file already exists'` error

**Comment by woct0rdho** [comment]
Yes indeed. Thank you for mentioning this!
