### ISSUE TITLE
[Solution] ERROR: triton-3.1.0-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by emmanuelwithme** [woct0rdho/triton-windows#24]
(inpaint) PS C:\image-inpaint-project> pip install https://github.com/woct0rdho/triton-windows/releases/download/v3.1.0-windows.post5/triton-3.1.0-cp310-cp310-win_amd64.whl
ERROR: triton-3.1.0-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.

if you are using python3.11 change command to:
`pip install https://github.com/woct0rdho/triton-windows/releases/download/v3.1.0-windows.post5/triton-3.1.0-cp311-cp311-win_amd64.whl`

**Comment by woct0rdho** [comment]
Exactly, you need to download the wheel according to your Python version
