### ISSUE TITLE
Test is OK, Triton works but still error when compile....

### ISSUE THREAD

**Issue by oliverban** [woct0rdho/triton-windows#25]
I have done the both tests outlined in the README (i.e the tensor test and the dll-tracer test) and both show that triton is installed correctly and working. But when compiling in ComfyUI I still get an error. Now I know the error says that my Cuda Capability is below 8.9 BUT the compilation did work for Cog a while and then something changed so I want to know WHAT might've changed to make the CC not be accepted anymore. I'm pretty sure 3090s are using the feature successfully.

My specs:
3090 w driver 566.14 (latest as of December)
CUDNN 9.6
CUDA 12.6
Visual Studio 2022 14.43
Python 3.12
Comfy UI is also latest as of December 9th
Torch 2.5.1+cu124

I am also attaching my ENV and my PATH specification if anyone can see something weird in them.

This is part of the error:
```
...
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 14 registers, used 0 barriers, 380 bytes cmem[0]
main.c
   Creating library main.lib and object main.exp
ptxas info    : 0 bytes gmem
ptxas info    : Compiling entry function 'triton_' for 'sm_86'
ptxas info    : Function properties for triton_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 11 registers, used 0 barriers, 380 bytes cmem[0]
E1209 21:52:30.538000 13612 venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py:445] [0/0] Triton compilation failed: triton_poi_fused__to_copy_1
E1209 21:52:30.538000 13612 venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py:445] [0/0] def triton_(in_ptr0, out_ptr0, xnumel, XBLOCK : tl.constexpr):
E1209 21:52:30.538000 13612 venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py:445] [0/0]     xnumel = 56623104
E1209 21:52:30.538000 13612 venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py:445] [0/0]     xoffset = tl.program_id(0) * XBLOCK
E1209 21:52:30.538000 13612 venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py:445] [0/0]     xindex = xoffset + tl.arange(0, XBLOCK)[:]
E1209 21:52:30.538000 13612 venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py:445] [0/0]     xmask = tl.full([XBLOCK], True, tl.int1)
E1209 21:52:30.538000 13612 venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py:445] [0/0]     x0 = xindex
E1209 21:52:30.538000 13612 venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py:445] [0/0]     tmp0 = tl.load(in_ptr0 + (x0), None)
E1209 21:52:30.538000 13612 venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py:445] [0/0]     tmp1 = tmp0.to(tl.float32)
E1209 21:52:30.538000 13612 venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py:445] [0/0]     tl.store(out_ptr0 + (x0), tmp1, None)
E1209 21:52:30.538000 13612 venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py:445] [0/0]
E1209 21:52:30.538000 13612 venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py:445] [0/0] metadata: {'signature': {0: '*fp8e4nv', 1: '*fp16', 2: 'i32'}, 'device': 0, 'constants': {3: 1024}, 'configs': [AttrsDescriptor(divisible_by_16=(0, 1, 2), equal_to_1=())], 'device_type': 'cuda', 'num_warps': 4, 'num_stages': 1, 'debug': True, 'cc': 86}
E1209 21:52:30.538000 13612 venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py:445] [0/0] Traceback (most recent call last):
E1209 21:52:30.538000 13612 venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py:445] [0/0]   File "C:\Users\Oliver\Documents\Github\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 1116, in visit_Call
E1209 21:52:30.538000 13612 venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py:445] [0/0]     return fn(*args, **extra_kwargs, **kws)
E1209 21:52:30.538000 13612 venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py:445] [0/0]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E1209 21:52:30.538000 13612 venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py:445] [0/0]   File "C:\Users\Oliver\Documents\Github\ComfyUI\venv\Lib\site-packages\triton\language\core.py", line 35, in wrapper
E1209 21:52:30.538000 13612 venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py:445] [0/0]     return fn(*args, **kwargs)
E1209 21:52:30.538000 13612 venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py:445] [0/0]            ^^^^^^^^^^^^^^^^^^^
E1209 21:52:30.538000 13612 venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py:445] [0/0]   File "C:\Users\Oliver\Documents\Github\ComfyUI\venv\Lib\site-packages\triton\language\core.py", line 993, in to
E1209 21:52:30.538000 13612 venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py:445] [0/0]     return semantic.cast(self, dtype, _builder, fp_downcast_rounding)
E1209 21:52:30.538000 13612 venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py:445] [0/0]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E1209 21:52:30.538000 13612 venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py:445] [0/0]   File "C:\Users\Oliver\Documents\Github\ComfyUI\venv\Lib\site-packages\triton\language\semantic.py", line 759, in cast
E1209 21:52:30.538000 13612 venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py:445] [0/0]     assert builder.options.allow_fp8e4nv, "fp8e4nv data type is not supported on CUDA arch < 89"
E1209 21:52:30.538000 13612 venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py:445] [0/0]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E1209 21:52:30.538000 13612 venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py:445] [0/0] AssertionError: fp8e4nv data type is not supported on CUDA arch < 89

```

<img width="558" alt="SystemPropertiesAdvanced_a9Fi4BkeOk" src="https://github.com/user-attachments/assets/56130c49-5520-410e-bda7-e060b2bd05bb">
<img width="654" alt="SystemPropertiesAdvanced_IGnDfkIkrm" src="https://github.com/user-attachments/assets/ea0e98f1-b49c-4abd-9d3d-87d9aedde4d2">

**Comment by woct0rdho** [comment]
Maybe you can try disabling fp8 in some ComfyUI nodes, or replacing fp8 with fp16 in the code

**Comment by oliverban** [comment]
> Maybe you can try disabling fp8 in some ComfyUI nodes, or replacing fp8 with fp16 in the code

The assert does reference fp8e4nv but on the node I am choosing fp8_e4m3fn, where does that other one come from?

**Comment by woct0rdho** [comment]
`fp8e4nv` and `fp8_e4m3fn` are just two names of the same thing. In general, there is no speed or memory boost when running fp8 on 30xx cards (CUDA arch 86)

**Comment by oliverban** [comment]
<img width="579" alt="ShareX_Kf37CtfRnP" src="https://github.com/user-attachments/assets/1f188287-dc4a-491d-8485-f17ec144557f">
Here's the error as it shows up in Comfy BTW! I've reinstalled triton, sage and VS Build Tools and still no go. CL in CMD shows MSVC is available to build, Triton tests all show OK and sage works without compile node connected. So everything is aligned BUT this thing I mention above which I don't know why it does.

**Comment by woct0rdho** [comment]
Did you disable fp8 in all nodes?

**Comment by oliverban** [comment]
> Did you disable fp8 in all nodes?

I did not. I don't think it'll fit on 24GB without FP8? The question still is why it shows a different FP8 quant arch, i.e: fp8e4nv instead of fp8_e4m3fn

**Comment by woct0rdho** [comment]
`fp8e4nv` and `fp8_e4m3fn` are just two names of the same dtype. See https://github.com/triton-lang/triton/blob/976c4e40984195d5f5b1ad0b91f5c1a504d8d28c/python/triton/runtime/jit.py#L421

**Comment by oliverban** [comment]
> `fp8e4nv` and `fp8_e4m3fn` are just two names of the same dtype. See https://github.com/triton-lang/triton/blob/976c4e40984195d5f5b1ad0b91f5c1a504d8d28c/python/triton/runtime/jit.py#L421

I see. But how come it has been supported on all other stuff except trion? 😅 I've been using FLUX `fp8_e4m3fn`, Cog `fp8_e4m3fn` and now Hunyuan `fp8_e4m3fn` ? Do you have any ideas on it?

**Comment by woct0rdho** [comment]
Currently fp8 is supported only in some special things like attention kernels, not general operations, while Triton is used to compile general operations. Even simple arithmetics like fp8 + fp8 are not implemented yet...

I guess it's possible to tell Triton to treat fp8 as if it's fp16 when fp8 is not supported. This should be a issue in the upstream Triton repo, not this repo
