### ISSUE TITLE
ImportError: DLL load failed while importing libtriton

### ISSUE THREAD

**Issue by Jonsen94** [woct0rdho/triton-windows#27]
Hello there,

I have problems during the import and need some help. I tried reinstalling and couldn't find any cache folders for removal.
Venv was created using uv
vcruntime140_1.dll vcruntime140.dll and msvcp140.dll were copied from the windows folder into the .venv/Scripts folder

Triton Version: 3.1.0
Torch version: 2.5.1+cu124

Error:

  File "[...]\.venv\lib\site-packages\triton\backends\amd\compiler.py", line 2, in <module>
    from triton._C.libtriton import ir, passes, llvm, amd
ImportError: DLL load failed while importing libtriton: Eine DLL-Initialisierungsroutine ist fehlgeschlagen.

Dlltracer output:

LoadLibrary C:\Windows\System32\kernel.appcore.dll
LoadLibrary C:\Windows\System32\apphelp.dll
LoadLibrary C:\Users\<username>\AppData\Local\Programs\Python\Python310\DLLs\_hashlib.pyd
LoadLibrary C:\Users\<username>\AppData\Local\Programs\Python\Python310\DLLs\libcrypto-1_1.dll
LoadLibrary <project_dir>\.venv\Lib\site-packages\triton\_C\libtriton.pyd
LoadLibrary C:\Users\<username>\AppData\Local\Programs\Python\Python310\vcruntime140_1.dll
LoadLibrary C:\Users\<username>\AppData\Local\Programs\Python\Python310\msvcp140.dll
LoadLibrary C:\Users\<username>\AppData\Local\Programs\Python\Python310\DLLs\_bz2.pyd
LoadLibrary C:\Users\<username>\AppData\Local\Programs\Python\Python310\DLLs\_lzma.pyd
LoadLibrary C:\Users\<username>\AppData\Local\Programs\Python\Python310\DLLs\_queue.pyd
LoadLibrary C:\Users\<username>\AppData\Local\Programs\Python\Python310\DLLs\_socket.pyd
LoadLibrary C:\Users\<username>\AppData\Local\Programs\Python\Python310\DLLs\select.pyd
LoadLibrary C:\Users\<username>\AppData\Local\Programs\Python\Python310\DLLs\_ssl.pyd
LoadLibrary C:\Windows\System32\crypt32.dll
LoadLibrary C:\Users\<username>\AppData\Local\Programs\Python\Python310\DLLs\libssl-1_1.dll

**Comment by woct0rdho** [comment]
Did dlltracer output some failed messages, like `Failed C:\Users\<username>\AppData\Local\Programs\Python\Python310\DLLs\...` ?

**Comment by Jonsen94** [comment]
Used the code from the readme, the output from above is the entire output (so no failed ...)

``` python
import sys
import dlltracer
with dlltracer.Trace(out=sys.stdout):
    import triton
```

**Comment by woct0rdho** [comment]
Ah, I see. your error message translates to 'A DLL initialization routine failed.' It may be the same as #13, and it's different from 'The specified module could not be found.'

I don't yet have a clear idea of how it happens, but maybe it's related to the venv

**Comment by Jonsen94** [comment]
I just did a visual studio reinstall with all packets, recopying all files and so on. Seems to work now but don't ask me why. No extra restart needed. 
It still does not work with pycharm, but I would bet thats an issue of pycharm and how it uses the venv.

For completeness: Ryzen 7 1800X
