### ISSUE TITLE
Installation (Where do I move the downloaded release to?)

### ISSUE THREAD

**Issue by ialhabbal** [woct0rdho/triton-windows#6]
I am on Windows 11, I installed all the requirements in the ReadMe and they work, I downloaded the release triton-3.1.0-cp311-cp311-win_amd64.whl since I have Cuda12.4.1 and embedded python 3.11.9 in ComfyUI, I moved the downloaded release to the embedded Python within ComfyUI (the two folders Include and Libs are there). I did pip install, and I got this error:

L:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded>pip install triton-3.1.0-cp311-cp311-win_amd64.whl
ERROR: triton-3.1.0-cp311-cp311-win_amd64.whl is not a supported wheel on this platform.

**Comment by NeoAnthropocene** [comment]
> L:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded>pip install triton-3.1.0-cp311-cp311-win_amd64.whl

Try this:
`"L:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\python.exe" -m pip install https://github.com/woct0rdho/triton-windows/releases/download/v3.1.0-windows.post4/triton-3.1.0-cp311-cp311-win_amd64.whl`
