### ISSUE TITLE
triton test.py creating folder in C:\Users\Username

### ISSUE THREAD

**Issue by shivshankar11** [woct0rdho/triton-windows#7]
why triton is creating folder in global location- C:\Users\Username\triton instead of its own local folder inside venv.
if i delete this folder this error is fixed.
ImportError: DLL load failed while importing cuda_utils: The specified module could not be found.
(venv) PS S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI> python test.py
main.c
   Creating library main.lib and object main.exp
ptxas info    : 0 bytes gmem
ptxas info    : Compiling entry function 'add_kernel' for 'sm_89'
ptxas info    : Function properties for add_kernel
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 26 registers, 380 bytes cmem[0]
main.c

this error always appeared whenever i change python version and i have to fix it by removing that folder.

**Comment by woct0rdho** [comment]
You can set the environment variable `TRITON_CACHE_DIR`
