### ISSUE TITLE
Triton 3.10 windows error: The system cannot find the file specified 

### ISSUE THREAD

**Issue by roman8ivanov** [woct0rdho/triton-windows#9]
I am getting error when run the test (see below).
Traceback (most recent call last):

  Cell In[4], line 1
    b_compiled = add(a, a)

  Cell In[2], line 17 in add
    add_kernel[grid](x, y, output, n_elements, BLOCK_SIZE=1024)

  File C:\ProgramData\anaconda3\Lib\site-packages\triton\runtime\jit.py:345 in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)

  File C:\ProgramData\anaconda3\Lib\site-packages\triton\runtime\jit.py:607 in run
    device = driver.active.get_current_device()

  File C:\ProgramData\anaconda3\Lib\site-packages\triton\runtime\driver.py:23 in __getattr__
    self._initialize_obj()

  File C:\ProgramData\anaconda3\Lib\site-packages\triton\runtime\driver.py:20 in _initialize_obj
    self._obj = self._init_fn()

  File C:\ProgramData\anaconda3\Lib\site-packages\triton\runtime\driver.py:9 in _create_driver
    return actives[0]()

  File C:\ProgramData\anaconda3\Lib\site-packages\triton\backends\nvidia\driver.py:414 in __init__
    self.utils = CudaUtils()  # TODO: make static

  File C:\ProgramData\anaconda3\Lib\site-packages\triton\backends\nvidia\driver.py:92 in __init__
    mod = compile_module_from_src(Path(os.path.join(dirname, "driver.c")).read_text(), "cuda_utils")

  File C:\ProgramData\anaconda3\Lib\site-packages\triton\backends\nvidia\driver.py:69 in compile_module_from_src
    so = _build(name, src_path, tmpdir, library_dirs(), include_dir, libraries)

  File C:\ProgramData\anaconda3\Lib\site-packages\triton\runtime\build.py:71 in _build
    ret = subprocess.check_call(cc_cmd)

  File C:\ProgramData\anaconda3\Lib\subprocess.py:408 in check_call
    retcode = call(*popenargs, **kwargs)

  File C:\ProgramData\anaconda3\Lib\subprocess.py:389 in call
    with Popen(*popenargs, **kwargs) as p:

  File C:\ProgramData\anaconda3\Lib\site-packages\spyder_kernels\customize\spydercustomize.py:109 in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File C:\ProgramData\anaconda3\Lib\subprocess.py:1026 in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,

  File C:\ProgramData\anaconda3\Lib\subprocess.py:1538 in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,

FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by woct0rdho** [comment]
Can you print out the content of `cc_cmd` before running `ret = subprocess.check_call(cc_cmd)`?

**Comment by woct0rdho** [comment]
Do you actually have this `cl.exe` in its folder? What happens if you open a new PowerShell and type `cl`?

**Comment by roman8ivanov** [comment]
![image](https://github.com/user-attachments/assets/7a45a9b2-4355-4787-b31f-5477f7928939)

**Comment by woct0rdho** [comment]
What is the path of that `cl.exe`? You can type `Get-Command cl` to show its path

(Things can get weird if one installs multiple versions of MSVC)

**Comment by roman8ivanov** [comment]
![image](https://github.com/user-attachments/assets/a22f7f12-388e-4faf-8865-fa61ebebc27b)

**Comment by woct0rdho** [comment]
So it seems you have installed multiple versions of MSVC. The one in your `PATH` is not the one found by Triton

(My code first try to find MSVC using `vswhere`, then using `PATH`. You can see the details in `windows_utils.py` in this repo)

Maybe you can uninstall all other versions of MSVC and only have one left, then try again

**Comment by roman8ivanov** [comment]
It is strange as I don't have this folder: 'c:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\Hostx64\\x64\\cl.exe'

**Comment by woct0rdho** [comment]
Before I thought that `vswhere` should be more reliable than `PATH` but now I'm not so sure... Maybe you can edit `triton/windows_utils.py`, remove the `find_msvc_base_vswhere()` part in the function `find_msvc()`, then try again

**Comment by roman8ivanov** [comment]
I keep getting the same error after removing find_msvc_base_vswhere() part in the function find_msvc(). 
![image](https://github.com/user-attachments/assets/69dfa15b-fc77-43a9-929e-722dd323cb03)
